### ISSUE TITLE
Bib for citation?

### ISSUE THREAD

**Issue by Shuailong** [MiuLab/LION-Net#1]
Hi I would like to cite your paper in my work and cannot find it on Arxiv etc. Is there any bib file available?

**Comment by tzutengweng33176** [comment]
Please use the following bibtex to cite this paper, thank you!
@ARTICLE {LION-Net,
    author  = "Kai-Ling Lo Ting-Wei Lu Tzu-teng Weng I-Hsuan Chen Yun-Nung Chen",
    title   = "LION-Net: LIghtweight ONtology-independent Networks for Schema-Guided Dialogue State Generation",
    journal = "DSTC8-track IV workshop paper",
    year    = "2020"
}
